/**
 * server.js
 * ---------
 * TLS chat server. Manages multiple simultaneous client connections, broadcasts
 * public messages, routes private messages, and provides basic admin controls.
 *
 * Usage:  node server.js [port]   (default port: 1599)
 *
 * Features:
 *  - Mutual TLS transport using a self-signed certificate
 *  - Public broadcast messages
 *  - End-to-end encrypted private messages (routed, not decrypted here)
 *  - User session key distribution for E2E encryption setup
 *  - Admin role with password authentication (SHA-256 hashed)
 *  - /ban command to kick and permanently block a user by ID
 *  - Keep-alive PING/PONG every 30 seconds
 *  - Per-client 1 MB receive buffer to prevent DoS attacks
 */

const tls    = require('tls');
const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

// ── Configuration ────────────────────────────────────────────────────────────

// Port can be overridden via the first CLI argument (set by terminal-chat.js)
const port = process.argv[2] ? parseInt(process.argv[2], 10) : 1599;

// TLS options: load the self-signed key/cert generated by postinstall.js
const options = {
  key:  fs.readFileSync(path.join(__dirname, 'server.key')),
  cert: fs.readFileSync(path.join(__dirname, 'server.crt'))
};

// ── Server state ─────────────────────────────────────────────────────────────

let clients   = [];              // array of active client objects (see structure below)
let bannedIds = new Set();       // set of user IDs that are not allowed to reconnect

// The admin password is stored only as a SHA-256 hash — the plaintext ("admin123")
// is never held in memory at runtime.
// ⚠️  Change this default password before deploying in any real environment!
const ADMIN_PASSWORD_HASH = crypto
  .createHash('sha256')
  .update('admin123')
  .digest('hex');

// Hard limit on unprocessed bytes per client connection to prevent memory exhaustion
const MAX_BUFFER = 1024 * 1024; // 1 MB

// ── Helper functions ─────────────────────────────────────────────────────────

/**
 * Writes a message to a socket, silently ignoring errors.
 * Using a wrapper prevents unhandled 'error' events from crashing the server
 * when writing to a socket that has just closed.
 *
 * @param {tls.TLSSocket} socket
 * @param {string} message
 */
function safeWrite(socket, message) {
  try {
    if (socket && !socket.destroyed) socket.write(message);
  } catch { /* ignore write errors on dead sockets */ }
}

/**
 * Broadcasts a message to every connected client, optionally skipping one
 * (typically the sender so they don't receive their own messages echoed back).
 *
 * @param {string}          message
 * @param {tls.TLSSocket}   [exceptSocket]  - Socket to skip
 */
function broadcast(message, exceptSocket = null) {
  clients.forEach(c => {
    if (c.socket !== exceptSocket) safeWrite(c.socket, message);
  });
}

/**
 * Looks up a connected client by their 4-char user ID.
 *
 * @param {string} id
 * @returns {{ name, id, key, socket, role, waitingForAdminPassword } | undefined}
 */
function getClientById(id) {
  return clients.find(c => c.id === id);
}

// ── Command handler ───────────────────────────────────────────────────────────

/**
 * Processes slash-commands typed by a connected client.
 * Only called after the initial handshake is complete.
 *
 * @param {string} cmd     - Full command string including the leading slash
 * @param {object} client  - The client object that sent the command
 */
function handleCommand(cmd, client) {
  const parts   = cmd.split(' ');
  const command = parts[0].toLowerCase();

  switch (command) {

    // List all available commands
    case '/help':
      safeWrite(client.socket,
        `Commands:\n/help\n/users\n/pm <ID> <msg>\n/admin\n/ban <ID>\n/ping\n/exit | /quit\n`
      );
      break;

    // Simple connectivity check — responds with a plain-text confirmation
    case '/ping':
      safeWrite(client.socket, 'Still connected\n');
      break;

    // List every online user with their ID and role
    case '/users':
      safeWrite(client.socket,
        `Online users (${clients.length}):\n` +
        clients.map(c =>
          `- [${c.id}] ${c.name}${c.role === 'admin' ? ' (admin)' : ''}`
        ).join('\n') + '\n'
      );
      break;

    // Begin the admin elevation flow — next input from this client is treated
    // as a password rather than a chat message (see waitingForAdminPassword flag)
    case '/admin':
      if (client.role === 'admin') return safeWrite(client.socket, 'Already admin\n');
      client.waitingForAdminPassword = true;
      safeWrite(client.socket, 'Enter admin password: ');
      break;

    // Ban a user by ID: disconnect them immediately and block future reconnects
    case '/ban': {
      if (client.role !== 'admin') {
        return safeWrite(client.socket, 'Permission denied\n');
      }
      const targetBan = getClientById(parts[1]);
      if (!targetBan) {
        return safeWrite(client.socket, 'User ID not found\n');
      }
      bannedIds.add(targetBan.id);                          // persist ban across reconnects
      safeWrite(targetBan.socket, 'You have been banned by admin\n');
      targetBan.socket.destroy();                           // forcibly close the connection
      clients = clients.filter(c => c !== targetBan);      // remove from active list
      broadcast(`<announce> User ${targetBan.name} was banned\n`);
      break;
    }

    // Gracefully close the client's connection
    case '/exit':
    case '/quit':
      safeWrite(client.socket, 'You have left the chat\n');
      client.socket.end(); // half-close so client receives the goodbye message
      break;

    default:
      safeWrite(client.socket, 'Unknown command. Try /help\n');
  }
}

// ── TLS server ───────────────────────────────────────────────────────────────

const server = tls.createServer(options, socket => {

  // Keep the TCP connection alive at the OS level even during idle periods
  socket.setKeepAlive(true);
  socket.setTimeout(0); // disable Node's built-in idle timeout (we use PING instead)

  // Per-connection state
  let client     = null;   // populated after the handshake JSON is parsed
  let dataBuffer = '';     // accumulates incoming bytes between 'data' events
  let pingInterval = null; // reference kept so we can cancel it on disconnect

  // ── Incoming data ──────────────────────────────────────────────────────────
  socket.on('data', data => {
    dataBuffer += data.toString();

    // Reject connections that send more than 1 MB without a newline —
    // this prevents a slow-loris-style memory exhaustion attack.
    if (dataBuffer.length > MAX_BUFFER) {
      safeWrite(socket, 'Error: message too large\n');
      socket.destroy();
      return;
    }

    // Split on newlines; keep the last (possibly incomplete) chunk in the buffer
    const lines = dataBuffer.split('\n');
    dataBuffer  = lines.pop();

    for (const raw of lines) {
      const msg = raw.trim();
      if (!msg) continue;

      // Silently discard keep-alive pong replies from the client
      if (msg === '__PONG__') continue;

      // ── Admin password prompt ─────────────────────────────────────────────
      // If this client just typed /admin, their very next message is treated as
      // the password — not as a chat message or command.
      if (client && client.waitingForAdminPassword) {
        client.waitingForAdminPassword = false;
        const inputHash = crypto.createHash('sha256').update(msg).digest('hex');
        if (inputHash === ADMIN_PASSWORD_HASH) {
          client.role = 'admin';
          safeWrite(client.socket, 'Admin access granted\n');
        } else {
          safeWrite(client.socket, 'Wrong password\n');
        }
        continue;
      }

      // ── Initial handshake (first message from a new connection) ───────────
      // Expected format: { name: string, id: string, key: string (hex) }
      if (!client) {
        try {
          const obj = JSON.parse(msg);

          // Reject banned users before they can join
          if (bannedIds.has(obj.id)) {
            safeWrite(socket, 'You are banned\n');
            socket.destroy();
            return;
          }

          // Register the new client
          client = {
            name:                   obj.name,
            id:                     obj.id,
            key:                    obj.key,  // hex-encoded E2E session key
            socket,
            role:                   'user',
            waitingForAdminPassword: false
          };
          clients.push(client);

          // Notify other users about the new joiner
          broadcast(`<announce> [${client.id}] ${client.name} joined\n`, socket);

          // Welcome message to the joining client
          safeWrite(socket, `Welcome ${client.name}! Your ID is [${client.id}]\n`);

          // Distribute the new client's E2E session key to all existing clients
          // so they can immediately send encrypted private messages to the newcomer.
          broadcast(
            JSON.stringify({ type: 'key_announce', id: client.id, key: client.key }) + '\n',
            socket
          );

          // Send the new client the session keys of every currently connected user
          // so the newcomer can send them private messages straight away.
          clients.forEach(c => {
            if (c !== client) {
              safeWrite(
                socket,
                JSON.stringify({ type: 'key_announce', id: c.id, key: c.key }) + '\n'
              );
            }
          });

        } catch {
          // Malformed or missing JSON handshake — reject immediately
          safeWrite(socket, 'Invalid handshake\n');
          socket.destroy();
        }
        continue;
      }

      // ── Slash commands ────────────────────────────────────────────────────
      if (msg.startsWith('/')) {
        handleCommand(msg, client);
        continue;
      }

      // ── Structured JSON message (private message) ─────────────────────────
      // The server only routes PM payloads — it never decrypts them.
      try {
        const obj = JSON.parse(msg);
        if (obj.type === 'pm') {
          const target = getClientById(obj.to);
          if (!target) {
            safeWrite(client.socket, 'User ID not found\n');
          } else {
            // Forward the entire encrypted payload verbatim to the recipient
            safeWrite(target.socket, msg + '\n');
          }
          continue;
        }
      } catch { /* not JSON — fall through to public broadcast */ }

      // ── Public broadcast message ──────────────────────────────────────────
      // Format: <DisplayName> message text
      broadcast(`<${client.name}> ${msg}\n`, socket);
    }
  });

  // ── Connection closed ──────────────────────────────────────────────────────
  socket.on('close', () => {
    // Always clear the ping timer immediately to avoid writing to a dead socket
    if (pingInterval) {
      clearInterval(pingInterval);
      pingInterval = null;
    }

    // Nothing to clean up if the client never completed the handshake
    if (!client) return;

    // Remove client from the active list and notify other users
    clients = clients.filter(c => c !== client);
    broadcast(`<announce> [${client.id}] ${client.name} left\n`);
  });

  // ── Socket-level errors ────────────────────────────────────────────────────
  // Log but don't crash — the 'close' event will still fire and clean up state.
  socket.on('error', err => {
    console.error('Socket error:', err.message);
  });

  // ── Keep-alive: ping every client every 30 seconds ────────────────────────
  // Detects dead connections that wouldn't otherwise trigger a 'close' event
  // (e.g., network drop without a TCP FIN/RST).
  pingInterval = setInterval(() => {
    if (socket.destroyed) {
      // Socket already gone — stop the timer to avoid accumulating dead intervals
      clearInterval(pingInterval);
      pingInterval = null;
    } else {
      safeWrite(socket, '__PING__\n');
    }
  }, 30000);
});

// ── Server-level error handler ────────────────────────────────────────────────
// Catches port-in-use (EADDRINUSE) and similar startup errors
server.on('error', err => {
  console.error('Server error:', err.message);
});

// ── Start listening ───────────────────────────────────────────────────────────
server.listen(port, () => {
  console.log(`🔐 Secure chat server running on port ${port}`);
});