/**
 * server.js
 * ---------
 * TLS chat server. Manages multiple simultaneous client connections, broadcasts
 * public messages, routes private messages, and provides basic admin controls.
 *
 * Usage:  node server.js [port]   (default port: 1599)
 *
 * Features:
 *  - Mutual TLS transport using a self-signed certificate
 *  - Public broadcast messages
 *  - End-to-end encrypted private messages (routed, not decrypted here)
 *  - User session key distribution for E2E encryption setup
 *  - Admin role with password authentication (SHA-256 hashed)
 *  - /ban command to kick and permanently block a user by ID
 *  - Keep-alive PING/PONG every 30 seconds
 *  - Per-client 1 MB receive buffer to prevent DoS attacks
 */

const tls    = require('tls');
const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

// ── Configuration ────────────────────────────────────────────────────────────

// Port can be overridden via the first CLI argument (set by terminal-chat.js)
const port = process.argv[2] ? parseInt(process.argv[2], 10) : 1599;

// TLS options: load the self-signed key/cert generated by postinstall.js
const options = {
  key:  fs.readFileSync(path.join(__dirname, 'server.key')),
  cert: fs.readFileSync(path.join(__dirname, 'server.crt'))
};

// ── Server state ─────────────────────────────────────────────────────────────

let clients   = [];              // array of active client objects (see structure below)
let bannedIds = new Set();       // set of user IDs that are not allowed to reconnect

// The admin password is stored only as a SHA-256 hash — the plaintext ("admin123")
// is never held in memory at runtime.
// ⚠️  Change this default password before deploying in any real environment!
const ADMIN_PASSWORD_HASH = crypto
  .createHash('sha256')
  .update('admin123')
  .digest('hex');

// Hard limit on unprocessed bytes per client connection to prevent memory exhaustion
const MAX_BUFFER = 1024 * 1024; // 1 MB

// ── File transfer configuration ─────────────────────────────────────────────

const FILES_DIR  = path.join(__dirname, 'files');       // permanent storage for uploaded files
const TMP_DIR    = path.join(FILES_DIR, '.tmp');         // in-progress uploads live here until finalized
const INDEX_PATH = path.join(FILES_DIR, 'index.json');   // persisted metadata: id -> {originalName, size, ...}

const MAX_FILE_SIZE    = 100 * 1024 * 1024;        // 100 MB per file
const FILE_TTL_MS      = 14 * 24 * 60 * 60 * 1000; // files are deleted 2 weeks after upload
const CLEANUP_INTERVAL = 60 * 60 * 1000;           // run the expiry sweep once an hour
const FILE_ID_CHARS    = 'abcdefghijklmnopqrstuvwxyz0123456789';
const FILE_ID_LENGTH   = 5;

// Make sure files/ and files/.tmp/ exist before we accept any connections
if (!fs.existsSync(FILES_DIR)) fs.mkdirSync(FILES_DIR, { recursive: true });
if (!fs.existsSync(TMP_DIR))   fs.mkdirSync(TMP_DIR,   { recursive: true });

// In-memory index of uploaded files, mirrored to disk so it survives server restarts.
// Structure: { [fileId]: { originalName, size, uploader, uploaderId, uploadedAt } }
let fileIndex = {};
if (fs.existsSync(INDEX_PATH)) {
  try {
    fileIndex = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf-8'));
  } catch {
    console.error('Warning: files/index.json was unreadable, starting with an empty index');
    fileIndex = {};
  }
}

function saveFileIndex() {
  try {
    fs.writeFileSync(INDEX_PATH, JSON.stringify(fileIndex, null, 2));
  } catch (err) {
    console.error('Failed to persist files/index.json:', err.message);
  }
}

// Generates a random 5-character [a-z0-9] ID, retrying on the rare collision
function generateFileId() {
  let id;
  do {
    id = '';
    for (let i = 0; i < FILE_ID_LENGTH; i++) {
      id += FILE_ID_CHARS[Math.floor(Math.random() * FILE_ID_CHARS.length)];
    }
  } while (fileIndex[id]);
  return id;
}

// Strips directory components so a crafted fileName (e.g. "../../etc/passwd")
// can never escape FILES_DIR or the client's download directory
function sanitizeFileName(name) {
  const base = path.basename(String(name || 'file'));
  return base.replace(/[\x00-\x1f]/g, '') || 'file';
}

// Deletes files whose 2-week retention has expired. Runs at startup and then
// on a recurring timer so nothing needs a per-file timer of its own.
function cleanupExpiredFiles() {
  const now = Date.now();
  let changed = false;
  for (const [id, meta] of Object.entries(fileIndex)) {
    if (now - meta.uploadedAt > FILE_TTL_MS) {
      fs.unlink(path.join(FILES_DIR, id), () => {}); // best-effort, ignore if already gone
      delete fileIndex[id];
      changed = true;
      console.log(`🗑️  Expired file removed: ${id} (${meta.originalName})`);
    }
  }
  if (changed) saveFileIndex();
}
cleanupExpiredFiles();
setInterval(cleanupExpiredFiles, CLEANUP_INTERVAL);

// ── Helper functions ─────────────────────────────────────────────────────────

/**
 * Writes a message to a socket, silently ignoring errors.
 * Using a wrapper prevents unhandled 'error' events from crashing the server
 * when writing to a socket that has just closed.
 *
 * @param {tls.TLSSocket} socket
 * @param {string} message
 */
function safeWrite(socket, message) {
  try {
    if (socket && !socket.destroyed) socket.write(message);
  } catch { /* ignore write errors on dead sockets */ }
}

/**
 * Broadcasts a message to every connected client, optionally skipping one
 * (typically the sender so they don't receive their own messages echoed back).
 *
 * @param {string}          message
 * @param {tls.TLSSocket}   [exceptSocket]  - Socket to skip
 */
function broadcast(message, exceptSocket = null) {
  clients.forEach(c => {
    if (c.socket !== exceptSocket) safeWrite(c.socket, message);
  });
}

/**
 * Looks up a connected client by their 4-char user ID.
 *
 * @param {string} id
 * @returns {{ name, id, key, socket, role, waitingForAdminPassword } | undefined}
 */
function getClientById(id) {
  return clients.find(c => c.id === id);
}

// ── File upload handlers ──────────────────────────────────────────────────────
// One upload at a time per connection; state lives on client.upload while active.

function handleFileUploadStart(client, obj) {
  if (client.upload) {
    return safeWrite(client.socket, JSON.stringify({ type: 'file_error', reason: 'An upload is already in progress' }) + '\n');
  }

  const size = Number(obj.size);
  if (!Number.isFinite(size) || size <= 0) {
    return safeWrite(client.socket, JSON.stringify({ type: 'file_error', reason: 'Invalid file size' }) + '\n');
  }
  if (size > MAX_FILE_SIZE) {
    return safeWrite(client.socket, JSON.stringify({
      type: 'file_error',
      reason: `File too large. Max allowed: ${MAX_FILE_SIZE / (1024 * 1024)} MB`
    }) + '\n');
  }

  const fileName = sanitizeFileName(obj.fileName);
  const tmpPath  = path.join(TMP_DIR, `${client.id}-${Date.now()}-${Math.random().toString(36).slice(2)}.part`);

  client.upload = {
    fileName,
    size,
    received: 0,
    tmpPath,
    stream: fs.createWriteStream(tmpPath)
  };

  client.upload.stream.on('error', err => {
    console.error('Upload write error:', err.message);
    safeWrite(client.socket, JSON.stringify({ type: 'file_error', reason: 'Server error while receiving file' }) + '\n');
    fs.unlink(tmpPath, () => {});
    client.upload = null;
  });

  safeWrite(client.socket, JSON.stringify({ type: 'file_upload_ready' }) + '\n');
}

function abortUpload(client, reason) {
  if (!client.upload) return;
  safeWrite(client.socket, JSON.stringify({ type: 'file_error', reason }) + '\n');
  client.upload.stream.destroy();
  fs.unlink(client.upload.tmpPath, () => {});
  client.upload = null;
}

function handleFileChunk(client, obj) {
  if (!client.upload) return; // stray chunk after an error/abort — ignore

  let buf;
  try {
    buf = Buffer.from(obj.chunk, 'base64');
  } catch {
    return abortUpload(client, 'Invalid chunk data');
  }

  client.upload.received += buf.length;
  if (client.upload.received > client.upload.size || client.upload.received > MAX_FILE_SIZE) {
    return abortUpload(client, 'Uploaded data exceeds declared size');
  }

  client.upload.stream.write(buf);
}

function handleFileUploadEnd(client) {
  if (!client.upload) return;
  const upload = client.upload;

  upload.stream.end(() => {
    if (!client.upload) return; // aborted while flushing to disk

    const fileId    = generateFileId();
    const finalPath = path.join(FILES_DIR, fileId);

    fs.rename(upload.tmpPath, finalPath, err => {
      if (err) {
        console.error('Failed to finalize upload:', err.message);
        safeWrite(client.socket, JSON.stringify({ type: 'file_error', reason: 'Server error while saving file' }) + '\n');
        fs.unlink(upload.tmpPath, () => {});
        client.upload = null;
        return;
      }

      fileIndex[fileId] = {
        originalName: upload.fileName,
        size:         upload.received,
        uploader:     client.name,
        uploaderId:   client.id,
        uploadedAt:   Date.now()
      };
      saveFileIndex();

      safeWrite(client.socket, JSON.stringify({ type: 'file_upload_ack', fileId }) + '\n');

      // Let everyone in the room know a new file is available and what its ID is
      broadcast(JSON.stringify({
        type:       'file_notice',
        fileId,
        fileName:   upload.fileName,
        size:       upload.received,
        uploader:   client.name,
        uploaderId: client.id
      }) + '\n');

      client.upload = null;
    });
  });
}

// ── File download ────────────────────────────────────────────────────────────

function sendFileToClient(client, fileId) {
  const meta = fileIndex[fileId];
  if (!meta) {
    return safeWrite(client.socket, `File not found: ${fileId}\n`);
  }

  const filePath = path.join(FILES_DIR, fileId);
  if (!fs.existsSync(filePath)) {
    delete fileIndex[fileId];
    saveFileIndex();
    return safeWrite(client.socket, `File not found on disk: ${fileId}\n`);
  }

  safeWrite(client.socket, JSON.stringify({
    type: 'file_download_start',
    fileId,
    fileName: meta.originalName,
    size: meta.size
  }) + '\n');

  const readStream = fs.createReadStream(filePath, { highWaterMark: 64 * 1024 });

  readStream.on('data', chunk => {
    const payload = JSON.stringify({
      type: 'file_download_chunk',
      fileId,
      chunk: chunk.toString('base64')
    }) + '\n';

    // Respect TCP backpressure: pause the file read if the socket's write buffer
    // is full, resume on 'drain'. Otherwise a fast disk + slow client could
    // balloon the server's memory with buffered writes for a 100MB file.
    const ok = client.socket.write(payload);
    if (!ok) {
      readStream.pause();
      client.socket.once('drain', () => readStream.resume());
    }
  });

  readStream.on('end', () => {
    safeWrite(client.socket, JSON.stringify({ type: 'file_download_end', fileId }) + '\n');
  });

  readStream.on('error', err => {
    console.error(`Error reading file ${fileId}:`, err.message);
    safeWrite(client.socket, JSON.stringify({ type: 'file_error', reason: 'Server error while reading file' }) + '\n');
  });
}

// ── Command handler ───────────────────────────────────────────────────────────

/**
 * Processes slash-commands typed by a connected client.
 * Only called after the initial handshake is complete.
 *
 * @param {string} cmd     - Full command string including the leading slash
 * @param {object} client  - The client object that sent the command
 */
function handleCommand(cmd, client) {
  const parts   = cmd.split(' ');
  const command = parts[0].toLowerCase();

  switch (command) {

    // List all available commands
    case '/help':
      safeWrite(client.socket,
        `Commands:\n/help\n/users\n/pm <ID> <msg>\n/sf <path>  (send a file)\n/gf <fileId>  (download a file)\n/admin\n/ban <ID>\n/ping\n/exit | /quit\n`
      );
      break;

    // Download a previously uploaded file by its 5-char ID
    case '/gf': {
      const fileId = parts[1];
      if (!fileId) return safeWrite(client.socket, 'Usage: /gf <fileId>\n');
      sendFileToClient(client, fileId);
      break;
    }

    // Simple connectivity check — responds with a plain-text confirmation
    case '/ping':
      safeWrite(client.socket, 'Still connected\n');
      break;

    // List every online user with their ID and role
    case '/users':
      safeWrite(client.socket,
        `Online users (${clients.length}):\n` +
        clients.map(c =>
          `- [${c.id}] ${c.name}${c.role === 'admin' ? ' (admin)' : ''}`
        ).join('\n') + '\n'
      );
      break;

    // Begin the admin elevation flow — next input from this client is treated
    // as a password rather than a chat message (see waitingForAdminPassword flag)
    case '/admin':
      if (client.role === 'admin') return safeWrite(client.socket, 'Already admin\n');
      client.waitingForAdminPassword = true;
      safeWrite(client.socket, 'Enter admin password: ');
      break;

    // Ban a user by ID: disconnect them immediately and block future reconnects
    case '/ban': {
      if (client.role !== 'admin') {
        return safeWrite(client.socket, 'Permission denied\n');
      }
      const targetBan = getClientById(parts[1]);
      if (!targetBan) {
        return safeWrite(client.socket, 'User ID not found\n');
      }
      bannedIds.add(targetBan.id);                          // persist ban across reconnects
      safeWrite(targetBan.socket, 'You have been banned by admin\n');
      targetBan.socket.destroy();                           // forcibly close the connection
      clients = clients.filter(c => c !== targetBan);      // remove from active list
      broadcast(`<announce> User ${targetBan.name} was banned\n`);
      break;
    }

    // Gracefully close the client's connection
    case '/exit':
    case '/quit':
      safeWrite(client.socket, 'You have left the chat\n');
      client.socket.end(); // half-close so client receives the goodbye message
      break;

    default:
      safeWrite(client.socket, 'Unknown command. Try /help\n');
  }
}

// ── TLS server ───────────────────────────────────────────────────────────────

const server = tls.createServer(options, socket => {

  // Keep the TCP connection alive at the OS level even during idle periods
  socket.setKeepAlive(true);
  socket.setTimeout(0); // disable Node's built-in idle timeout (we use PING instead)

  // Per-connection state
  let client     = null;   // populated after the handshake JSON is parsed
  let dataBuffer = '';     // accumulates incoming bytes between 'data' events
  let pingInterval = null; // reference kept so we can cancel it on disconnect

  // ── Incoming data ──────────────────────────────────────────────────────────
  socket.on('data', data => {
    dataBuffer += data.toString();

    // Reject connections that send more than 1 MB without a newline —
    // this prevents a slow-loris-style memory exhaustion attack.
    if (dataBuffer.length > MAX_BUFFER) {
      safeWrite(socket, 'Error: message too large\n');
      socket.destroy();
      return;
    }

    // Split on newlines; keep the last (possibly incomplete) chunk in the buffer
    const lines = dataBuffer.split('\n');
    dataBuffer  = lines.pop();

    for (const raw of lines) {
      const msg = raw.trim();
      if (!msg) continue;

      // Silently discard keep-alive pong replies from the client
      if (msg === '__PONG__') continue;

      // ── Admin password prompt ─────────────────────────────────────────────
      // If this client just typed /admin, their very next message is treated as
      // the password — not as a chat message or command.
      if (client && client.waitingForAdminPassword) {
        client.waitingForAdminPassword = false;
        const inputHash = crypto.createHash('sha256').update(msg).digest('hex');
        if (inputHash === ADMIN_PASSWORD_HASH) {
          client.role = 'admin';
          safeWrite(client.socket, 'Admin access granted\n');
        } else {
          safeWrite(client.socket, 'Wrong password\n');
        }
        continue;
      }

      // ── Initial handshake (first message from a new connection) ───────────
      // Expected format: { name: string, id: string, key: string (hex) }
      if (!client) {
        try {
          const obj = JSON.parse(msg);

          // Reject banned users before they can join
          if (bannedIds.has(obj.id)) {
            safeWrite(socket, 'You are banned\n');
            socket.destroy();
            return;
          }

          // Register the new client
          client = {
            name:                   obj.name,
            id:                     obj.id,
            key:                    obj.key,  // hex-encoded E2E session key
            socket,
            role:                   'user',
            waitingForAdminPassword: false,
            upload:                  null      // holds { fileName, size, received, tmpPath, stream } during an active /sf upload
          };
          clients.push(client);

          // Notify other users about the new joiner
          broadcast(`<announce> [${client.id}] ${client.name} joined\n`, socket);

          // Welcome message to the joining client
          safeWrite(socket, `Welcome ${client.name}! Your ID is [${client.id}]\n`);

          // Distribute the new client's E2E session key to all existing clients
          // so they can immediately send encrypted private messages to the newcomer.
          broadcast(
            JSON.stringify({ type: 'key_announce', id: client.id, key: client.key }) + '\n',
            socket
          );

          // Send the new client the session keys of every currently connected user
          // so the newcomer can send them private messages straight away.
          clients.forEach(c => {
            if (c !== client) {
              safeWrite(
                socket,
                JSON.stringify({ type: 'key_announce', id: c.id, key: c.key }) + '\n'
              );
            }
          });

        } catch {
          // Malformed or missing JSON handshake — reject immediately
          safeWrite(socket, 'Invalid handshake\n');
          socket.destroy();
        }
        continue;
      }

      // ── Slash commands ────────────────────────────────────────────────────
      if (msg.startsWith('/')) {
        handleCommand(msg, client);
        continue;
      }

      // ── Structured JSON message (private message) ─────────────────────────
      // The server only routes PM payloads — it never decrypts them.
      try {
        const obj = JSON.parse(msg);
        if (obj.type === 'pm') {
          const target = getClientById(obj.to);
          if (!target) {
            safeWrite(client.socket, 'User ID not found\n');
          } else {
            // Forward the entire encrypted payload verbatim to the recipient
            safeWrite(target.socket, msg + '\n');
          }
          continue;
        }

        // ── File transfer (upload side) ──────────────────────────────────────
        if (obj.type === 'file_upload_start') { handleFileUploadStart(client, obj); continue; }
        if (obj.type === 'file_chunk')        { handleFileChunk(client, obj);       continue; }
        if (obj.type === 'file_upload_end')   { handleFileUploadEnd(client);        continue; }
      } catch { /* not JSON — fall through to public broadcast */ }

      // ── Public broadcast message ──────────────────────────────────────────
      // Format: <DisplayName> message text
      broadcast(`<${client.name}> ${msg}\n`, socket);
    }
  });

  // ── Connection closed ──────────────────────────────────────────────────────
  socket.on('close', () => {
    // Always clear the ping timer immediately to avoid writing to a dead socket
    if (pingInterval) {
      clearInterval(pingInterval);
      pingInterval = null;
    }

    // Nothing to clean up if the client never completed the handshake
    if (!client) return;

    // Abandon any in-progress upload so its temp file doesn't linger forever
    if (client.upload) {
      client.upload.stream.destroy();
      fs.unlink(client.upload.tmpPath, () => {});
      client.upload = null;
    }

    // Remove client from the active list and notify other users
    clients = clients.filter(c => c !== client);
    broadcast(`<announce> [${client.id}] ${client.name} left\n`);
  });

  // ── Socket-level errors ────────────────────────────────────────────────────
  // Log but don't crash — the 'close' event will still fire and clean up state.
  socket.on('error', err => {
    console.error('Socket error:', err.message);
  });

  // ── Keep-alive: ping every client every 30 seconds ────────────────────────
  // Detects dead connections that wouldn't otherwise trigger a 'close' event
  // (e.g., network drop without a TCP FIN/RST).
  pingInterval = setInterval(() => {
    if (socket.destroyed) {
      // Socket already gone — stop the timer to avoid accumulating dead intervals
      clearInterval(pingInterval);
      pingInterval = null;
    } else {
      safeWrite(socket, '__PING__\n');
    }
  }, 30000);
});

// ── Server-level error handler ────────────────────────────────────────────────
// Catches port-in-use (EADDRINUSE) and similar startup errors
server.on('error', err => {
  console.error('Server error:', err.message);
});

// ── Start listening ───────────────────────────────────────────────────────────
server.listen(port, () => {
  console.log(`🔐 Secure chat server running on port ${port}`);
});
